## Matrices operations

In [1]:
import numpy as np

In [2]:
# ex1: matrix multiplication
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
c = np.matmul(a, b)
print (c)

[[4 1]
 [2 2]]


In [3]:
# ex2: Transpose
print(c)
print()
print(c.T)

[[4 1]
 [2 2]]

[[4 2]
 [1 2]]


In [4]:
# ex3: element-wise multiplication
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

y=np.multiply(x1,x2)
print(y)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [5]:
# ex4: same as elementwise multiplication
z=x1*x2
print(z)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [6]:
# ex5: broadcasting
a = np.array([17, 11, 19]) # 1x3 Dimension array
print(a.shape)
print(a)
b = 3 
print(b)
 
# Broadcasting happened because of
# miss match in array Dimension.
c = a + b  # a= [17, 11, 19] b= [3,3,3]
print(c)

(3,)
[17 11 19]
3
[20 14 22]


In [7]:
# ex6: broadcasting
A = np.array([[11, 22, 33], [10, 20, 30]]) # 2x3
print(A)
 
b = 4
print(b)
 
C = A + b
print(C)

[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


In [8]:
# ex7: broadcarsting

observation = np.array([111.0, 188.0]) # (2,)
codes = np.array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]]) # (4x2) 

diff = codes - observation    # the broadcast happens here
print(diff)
print()

# first you do element wise square, then you sum each row column value, 
# then you perform elementwise sqrt 
dist = np.sqrt(np.sum(diff**2,axis=-1)) # axis = 1
print(dist)
print()

# return minimum value index
minidx = np.argmin(dist)
print(minidx)
print()

# return maximum value index
maxidx = np.argmax(dist)
print(maxidx)

[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]]

[17.49285568 21.58703314 73.79024326 56.04462508]

0

2


In [9]:
# arange
# numpy.arange([start, ]stop, [step, ])

# ex8
print(np.arange(-3, 3, 0.5, dtype=float))
print(np.arange(3))
print(np.arange(3.0))
print(np.arange(3,7))
print(np.arange(3,7,2))

[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5]
[0 1 2]
[0. 1. 2.]
[3 4 5 6]
[3 5]


In [10]:
# zeros and ones array-----"""

# ex9
# use np.zeros or np.ones
print(np.zeros(5)) # default: float
print(np.zeros((5,), dtype=int)) # default: dtype=float
print(np.zeros((2, 1))) # or [2,1]

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0.]
 [0.]]


In [11]:
# Some fundemental functions 

# ex10
a = np.array([[1, 2], [3, 4]]) 

# mean or average
print(np.mean(a)) # return mean from entire matrix
print(np.mean(a, axis=0)) # columnwise x-axis
print(np.mean(a, axis=1)) # rowwise y-axis

# minumum
print(np.min(a)) # min of entire matrix
print(np.min(a,axis=0))
print(np.min(a,axis=1))

# maximum
print(np.max(a)) # max of entire matrix

# standard deviation
print(np.std(a)) # you can also use axis

2.5
[2. 3.]
[1.5 3.5]
1
[1 2]
[1 3]
4
1.118033988749895
