## Creating Arrays

In [1]:
# you need to import the package for numpy
import numpy as np

In [2]:
# ex1: creating numpy array object
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(type(arr[0]))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [3]:
# ex2: 0-D array - just a scalar number
arr = np.array(42)
print(arr)

42


In [4]:
# ex3: 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
# ex4: 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# ex5: 3D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr.shape)

(2, 2, 3)


In [7]:
# ex6: check dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(d.shape)
print(d.shape[0])
print(d.shape[1])
print(d.shape[2])
print(d.shape[-1])

x,y,z = d.shape

print(z)

(2, 2, 3)
2
2
3
3
3


## Access Array Elements

In [9]:
# ex7: access elements
arr = np.array([1, 2, 3, 4])
print(arr[-2])
print(arr[0])

3
1


In [10]:
# ex: accesing 2D list is different than 2D numpy array
l = list()
x = [1,2,3,4,5]

for i in range(2):
    l.append(x)

print(l)

# print(l[1, 4]) TypeError: list indices must be integers or slices, not tuple
print(l[1][4])


[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
5


In [11]:
# ex8: 2D access
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('5th element on 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row:  10


In [12]:
# ex9: 3D access
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


# Array Slicing

In [13]:
# ex10
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [14]:
# ex11
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [15]:
# ex12
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [16]:
# ex13
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [17]:
# ex14: step
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [18]:
# ex15: From the second element, slice elements from index 1 to index 4 (not included)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [19]:
# ex16: From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [20]:
# ex: return multi indexed 2D numpy array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr2 = arr[0:2, 0:2]
print(arr2)
print(type(arr2))

[[1 2]
 [6 7]]
<class 'numpy.ndarray'>


In [21]:
# ex17: From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Array Shape

In [22]:
# The shape of an array is the number of elements in each dimension.

# ex18: return all dimension
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
a,b = arr.shape
print(a)

(2, 4)
2


In [23]:
# ex19: return specific dimension
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape[0]) # zero axis
print(arr.shape[1]) # first axis

2
4


# Reshaping arrays

In [24]:
# ex20: Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)
newarr = arr.reshape(4, 3)
print(newarr.shape)

(12,)
(4, 3)


In [25]:
a = np.array([1,2,3,4,5,6])
b = np.reshape(a,(2,3))
print(a)
b = a.reshape((2,3))
print(a)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [26]:
# ex21: Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [27]:
# ex22: Unknown Dimension
#You are allowed to have one "unknown" dimension.
#Meaning that you do not have to specify an exact number for one 
#of the dimensions in the reshape method.
#Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# ex23: Flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
newarr = arr.reshape(-1)
print(newarr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [29]:
# ex23: Flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print()
newarr = arr.flatten()
print(newarr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


# Array Iterating

In [30]:
# ex24:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [31]:
# ex25:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [32]:
# ex26: nested iteration
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) # print row vector
  for y in x:
    print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [33]:
# ex27: 3D array iteration
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)
  print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]



In [34]:
# ex28: nested iteration
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)
  for y in x:
    print(y)
    for z in y:
      print(z)
  print()

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6

[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12

