## Random Numbers in NumPy

In [1]:
from numpy import random
import numpy as np

In [2]:
# random number generator seeding that means 
# when you restart computer same random numbers
np.random.seed(1337)

In [3]:
# ex1: Generate a random integer from 0 to 100
x = random.randint(100)
print(x)

23


In [4]:
# ex2: The random module's rand() method returns a random float between 0 and 1.
x = random.rand()
print(x)

0.5605297472974954


In [5]:
# ex3: Generate Random Array
x=random.randint(100, size=(5))
print(x)

[39 89 39 90 82]


In [6]:
# ex4
x = random.randint(100, size=(3, 5))
print(x)

[[84 72  9  6 54]
 [90 23 24  1 27]
 [93  6 22 66 75]]


In [7]:
# ex5
x = random.rand(5)
print(x)

[0.44322487 0.78955834 0.79411858 0.36126157 0.41610394]


In [8]:
# ex6
x = random.rand(3, 5)
print(x)

[[0.58425813 0.76017177 0.18780841 0.28816715 0.67021886]
 [0.49964826 0.17856868 0.4131413  0.19919524 0.5316994 ]
 [0.8323707  0.18525095 0.95735922 0.42541467 0.50400704]]


In [9]:
# ex: generate random real number number between [minx, maxx]
minx = -3
maxx = 3
x = (maxx-minx)*random.rand(3, 5)+minx
print(x)

[[ 0.06282568 -2.90525129  1.39014041  2.95983024 -2.0227348 ]
 [-2.24019132 -0.75099489  1.15931667 -2.98259382 -0.78462563]
 [-2.64792405  1.73601651 -0.90138472  1.21514232 -0.05262554]]


In [10]:
# ex7: Generate Random Number From Array
#The choice() method allows you to generate a random value 
#based on an array of values.

#The choice() method takes an array as a parameter and randomly 
#returns one of the values.

x = random.choice([3, 5, 7, 9])
print(x)

5


In [11]:
x = np.arange(100) # generate a vector sequencially from 0 to 99 
print(x)

a = random.choice(x)
b = a
while b == a: # this continue until b and a are different
    b = random.choice(x)

print(f"a:{a}\nb:{b}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
a:98
b:48
